### ISSUE TITLE
use the script two times

### ISSUE THREAD

**Issue by bratgeraet** [andrewbiggart/latest-tweets-php-o-auth#15]
I want to show two different Twitter feeds on the same page.
I put the script in two different folders on the server and configered for the Twitter profiles.
The server loads only one feed and show a warning message that variables already declare.
My PHP skills are very low.
Is it possible to run it like I want to do?

**Comment by andrewbiggart** [comment]
Hi Bratgeraet,

You don't need to create two different versions of the script to achieve this.

The script is a function, so can be used as many times as you like.

Simple add this line to the bottom of the tweets.php file for the second feed:

display_latest_tweets('second_twitter_account');


Andrew

**Comment by bratgeraet** [comment]
works great, thank you!

**Comment by andrewbiggart** [comment]
The only thing you need to consider, is having separate cache files for booth feeds.

**Comment by bratgeraet** [comment]
I use it with one cache file and it works...

**Comment by bratgeraet** [comment]
ok now it seems to work.
i make a copy of function display_latest_tweets and call it display_latest_tweets2 and rename all variables
